//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMdev.Calculator.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RMdev.Calculator.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Identifying {0}..
        /// </summary>
        internal static string ErrorIdentifying {
            get {
                return ResourceManager.GetString("ErrorIdentifying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no {0} to the power of {1}..
        /// </summary>
        internal static string PowNaN {
            get {
                return ResourceManager.GetString("PowNaN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The word &apos;{0}&apos; is reserved..
        /// </summary>
        internal static string ReservedWord {
            get {
                return ResourceManager.GetString("ReservedWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The word &apos;{0}&apos; is reserved for a custom function..
        /// </summary>
        internal static string ReservedWordForCustomFunction {
            get {
                return ResourceManager.GetString("ReservedWordForCustomFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no root {1} of {0}..
        /// </summary>
        internal static string RootNaN {
            get {
                return ResourceManager.GetString("RootNaN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no square root of {0}..
        /// </summary>
        internal static string SqrtNaN {
            get {
                return ResourceManager.GetString("SqrtNaN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The variable &apos;{0}&apos; has not been defined..
        /// </summary>
        internal static string UndefinedVariable {
            get {
                return ResourceManager.GetString("UndefinedVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected Character..
        /// </summary>
        internal static string UnexpectedCharacter {
            get {
                return ResourceManager.GetString("UnexpectedCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An empty lexeme is not expected here..
        /// </summary>
        internal static string UnexpectedEmptyLexeme {
            get {
                return ResourceManager.GetString("UnexpectedEmptyLexeme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The end of expression was not expected..
        /// </summary>
        internal static string UnexpectedFinalLexeme {
            get {
                return ResourceManager.GetString("UnexpectedFinalLexeme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The lexeme &apos;{0}&apos; was not expected here..
        /// </summary>
        internal static string UnexpectedLexeme {
            get {
                return ResourceManager.GetString("UnexpectedLexeme", resourceCulture);
            }
        }
    }
}
